'use client';

import Link from 'next/link';
import { ArrowRight, Check, FileCheck2, LifeBuoy, MessageCircle, ShieldCheck, Users, Wrench } from 'lucide-react';
import { useI18n } from '@/lib/i18n';
import { discordUrl } from '@/lib/contact';

export function AboutPage() {
  const { locale } = useI18n();
  const de = locale === 'de';
  return <main className="company-page container-wide"><section className="company-hero"><div><span className="eyebrow-duo"><Users size={14} /> DuoNerds / {de ? 'Ãœber uns' : 'About'}</span><h1>{de ? 'Direkter Austausch. Saubere Technik. Kein Theater.' : 'Direct communication. Solid technology. No theatre.'}</h1><p className="portal-lead">{de ? 'DuoNerds ist ein kleines Game-Tech-Studio fÃ¼r Projekte, die irgendwo zwischen Idee, bestehendem Code und â€ždas mÃ¼sste eigentlich gehenâ€œ liegen. Wir helfen dir, daraus einen machbaren nÃ¤chsten Schritt zu machen.' : 'DuoNerds is a small game-tech studio for projects somewhere between an idea, existing code and â€œthis should work somehowâ€. We help turn that into a useful next step.'}</p><div className="hero-actions"><Link className="button-duo button-primary" href="/#kontakt">{de ? 'Projekt besprechen' : 'Discuss a project'} <ArrowRight size={15} /></Link><Link className="button-duo button-ghost" href="/projekte">{de ? 'Arbeitsproben ansehen' : 'View work samples'} <ArrowRight size={15} /></Link></div></div><div className="company-hero-note"><span className="company-note-mark">DN</span><p>{de ? 'Wir sagen dir auch, wenn ein anderer Weg sinnvoller, kleiner oder gerade noch nicht dran ist.' : 'We will also tell you when another route, a smaller scope or a later start makes more sense.'}</p></div></section><section className="company-principles"><div className="company-principle"><span>01</span><h2>{de ? 'Wir sortieren zuerst.' : 'We shape first.'}</h2><p>{de ? 'Nicht jede Idee braucht sofort ein groÃŸes System. Wir klÃ¤ren Ziel, Grenzen und den kleinsten sinnvollen Start.' : 'Not every idea needs a large system immediately. We clarify goal, boundaries and the smallest useful start.'}</p></div><div className="company-principle"><span>02</span><h2>{de ? 'Wir zeigen ZwischenstÃ¤nde.' : 'We show progress.'}</h2><p>{de ? 'Du musst nicht bis zur Ãœbergabe warten, um zu wissen, ob die Richtung stimmt.' : 'You do not have to wait until handover to know whether the direction is right.'}</p></div><div className="company-principle"><span>03</span><h2>{de ? 'Wir lassen dich nicht allein.' : 'We do not leave you alone.'}</h2><p>{de ? 'Ãœbergabe, Dokumentation und Support sind Teile der Arbeit â€“ keine nachtrÃ¤gliche FuÃŸnote.' : 'Handover, documentation and support are part of the work, not an afterthought.'}</p></div></section><section className="company-callout"><div><span className="eyebrow-duo">{de ? 'Unser MaÃŸstab' : 'Our standard'}</span><h2>{de ? 'Wenn es kompliziert wird, werden wir verstÃ¤ndlicher.' : 'When it gets complex, we become clearer.'}</h2></div><Link className="text-link" href="/calculator">{de ? 'Planung starten' : 'Start planning'} <ArrowRight size={14} /></Link></section></main>;
}

export function SupportPage() {
  const { locale } = useI18n();
  const de = locale === 'de';
  const cards = de ? [
    { icon: Wrench, title: 'Bugfix & Stabilisierung', text: 'Ein bestehendes System verhÃ¤lt sich anders als erwartet? Wir grenzen ein, dokumentieren und beheben mit nachvollziehbarem Scope.' },
    { icon: ShieldCheck, title: 'Wartung & Betrieb', text: 'Versionen, Deployments und kleine Anpassungen sollen nicht jedes Mal bei null beginnen.' },
    { icon: FileCheck2, title: 'Review & Ãœbergabe', text: 'Du brauchst eine ehrliche EinschÃ¤tzung, bevor du weiter investierst? Wir prÃ¼fen Struktur, Risiken und nÃ¤chste Schritte.' },
  ] : [
    { icon: Wrench, title: 'Bugfix & stabilization', text: 'Something behaves differently than expected? We narrow it down, document it and fix it with a clear scope.' },
    { icon: ShieldCheck, title: 'Maintenance & operations', text: 'Versions, deployments and small adjustments should not restart from zero every time.' },
    { icon: FileCheck2, title: 'Review & handover', text: 'Need an honest assessment before investing further? We review structure, risks and next steps.' },
  ];
  return <main className="company-page container-wide"><section className="company-hero support-hero"><div><span className="eyebrow-duo"><LifeBuoy size={14} /> DuoNerds / Support</span><h1>{de ? 'Wenn etwas nicht weitergeht, gehen wir es gemeinsam durch.' : 'When something stops moving, we work through it with you.'}</h1><p className="portal-lead">{de ? 'Support ist fÃ¼r uns nicht nur ein Discord-Kanal. Es geht um Einordnung, klare Antworten und einen Zustand, mit dem du weiterarbeiten kannst.' : 'Support is not just a Discord channel to us. It means context, clear answers and a state you can actually continue working with.'}</p><div className="hero-actions"><a className="button-duo button-primary" href={discordUrl} target="_blank" rel="noreferrer"><MessageCircle size={15} /> Discord Ã¶ffnen</a><Link className="button-duo button-ghost" href="/#kontakt">Anfrage senden <ArrowRight size={15} /></Link></div></div><div className="support-status"><span className="status-dot" /><strong>{de ? 'Direkter Austausch' : 'Direct exchange'}</strong><p>{de ? 'Kurze Beschreibung reicht. Wir sortieren den Rest mit dir.' : 'A short description is enough. We will shape the rest with you.'}</p></div></section><section className="support-grid">{cards.map((card) => <article className="support-card" key={card.title}><span className="support-card-icon"><card.icon size={19} /></span><h2>{card.title}</h2><p>{card.text}</p><span className="support-card-check"><Check size={13} /> {de ? 'klarer nÃ¤chster Schritt' : 'clear next step'}</span></article>)}</section><section className="company-callout"><div><span className="eyebrow-duo">{de ? 'Nicht sicher, wo du anfangen sollst?' : 'Not sure where to start?'}</span><h2>{de ? 'ErzÃ¤hl uns einfach, was gerade nicht funktioniert.' : 'Tell us what is not working right now.'}</h2></div><Link className="text-link" href="/projekte">Arbeitsweise ansehen <ArrowRight size={14} /></Link></section></main>;
}

